[package]
name = "akcleaner"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
cliclack = "0.5.6"
console = "0.16"
garde = { version = "0.22", features = ["derive"] }
jsonc-parser = { version = "0.33.2", features = ["cst"] }
rustix = { version = "1", features = ["fs"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
thiserror = "2"

[dev-dependencies]
tempfile = "3"
